syntax = "proto3";
package messagebase;

import "google/protobuf/timestamp.proto";
import "google/protobuf/field_mask.proto";

option go_package = "main/proto";

service MessageService {
  rpc CreateMessage (CreateMessageRequest) returns (CreateMessageResponse);
  rpc ListMessages (ListMessagesRequest) returns (ListMessagesResponse);
  rpc UpdateMessage (UpdateMessageRequest) returns (UpdateMessageResponse);
}

message Message {
  int64                     id              = 1;
  int64                     conversation_id = 2;
  int64                     sender_id       = 3;
  string                    content         = 4;
  google.protobuf.Timestamp created_at      = 5;
  bool                      is_read         = 6;
}

message CreateMessageRequest {
  int64  conversation_id = 1;
  int64  sender_id       = 2;
  string content         = 3;
}

message CreateMessageResponse {
  Message message = 1;
}

message ListMessagesRequest {
  int64 conversation_id = 1;
  optional int64 last_message_id = 2;
}

message ListMessagesResponse{
  repeated Message messages = 1;
}

message UpdateMessageRequest {
  Message message = 1;
  google.protobuf.FieldMask field_mask = 2;
}

message UpdateMessageResponse {
  Message message = 1;
}
