syntax = "proto3";
package propertylist;

import "property-base/proto/property-api.proto";

option go_package = "main/proto";

service PropertyListService {
  rpc ListProperties (ListPropertiesRequest)  returns (ListPropertiesResponse);
  rpc CountProperties(CountPropertiesRequest) returns (CountPropertiesResponse);
}

enum SortType {
  SORT_TYPE_UNSPECIFIED = 0;
  SORT_TYPE_NAME        = 1;
  SORT_TYPE_PRICE_ASC   = 2;
  SORT_TYPE_PRICE_DESC  = 3;
}

message ListPropertiesRequest {
  string                              next_page_token = 1;
  int64                               page_size       = 2;
  repeated ListPropertiesFiltersOneOf filters         = 3;
  SortType                            sort_type       = 4;
}

message ListPropertiesFiltersOneOf {
  oneof filter {
    FilterByOwner        owner         = 1;
    FilterByName         name          = 2;
    FilterByLocation     location      = 3;
    FilterByPriceRange   price_range   = 4;
    FilterByDateInterval date_interval = 5;
  }
}

message FilterByName {
  string value = 1;
}

message FilterByLocation {
  property.Location center = 1;
  float             radius = 2;
}

message FilterByOwner {
  int64 value = 1;
}

message FilterByPriceRange {
  int64 min = 1;
  int64 max = 2;
}

message FilterByDateInterval {
  string check_in_date  = 1;
  string check_out_date = 2;
}

message ListPropertiesResponse {
  string                     next_page_token = 1;
  repeated property.Property properties      = 2;
}

message CountPropertiesRequest {
  repeated ListPropertiesFiltersOneOf filters = 1;
}

message CountPropertiesResponse {
  int64 count = 1;
}
