syntax = "proto3";
package gateway;

import "user-base/proto/user-api.proto";
import "friend-request-base/proto/friend-request-api.proto";
import "common/google/api/annotations.proto";

option go_package = "main/proto";

service GatewayService {
    rpc CreateUser(userbase.CreateUserRequest) returns (userbase.CreateUserResponse){
        option (google.api.http) = {
            post: "/createuser"
            body: "*"
        };
    }
    rpc CreateFriendRequestEndpoint (friendrequestbase.CreateFriendRequestRequest) returns (friendrequestbase.CreateFriendRequestResponse){
        option (google.api.http) = {
            post: "/friendrequest"
            body: "*"
        };
      }


} 