syntax = "proto3";
package userbase;

import "google/protobuf/timestamp.proto";
import "google/protobuf/field_mask.proto";

option go_package = "main/proto";

service UserService {
    rpc CreateUser(CreateUserRequest) returns (CreateUserResponse);
    rpc GetUser(GetUserRequest) returns (GetUserResponse) ;
    rpc ListUsers(ListUsersRequest) returns (ListUsersResponse);
    rpc UpdateUser (UpdateUserRequest) returns (UpdateUserResponse);
    rpc DeleteUser (DeleteUserRequest) returns (DeleteUserResponse);
} 

message User {
  int64 id = 1;
  string first_name = 2;
  string last_name = 3;
  string user_name = 4;
  string email = 5;
  string password = 6;
  google.protobuf.Timestamp created_at = 7; 
}

message CreateUserRequest{
    User user = 1;
}

message CreateUserResponse{
    User user = 1;
}

message GetUserRequest{
    string email = 1;
}

message GetUserResponse{
    User user = 1;
}

message ListUsersRequest{
    string nextPageToken = 1;
    int64 pageSize = 2;
    repeated ListUsersFiltersOneOf filters = 3;
}

message ListUsersResponse{   
    string nextPageToken = 1;
    repeated User users = 2; 
}

message ListUsersFiltersOneOf {
    oneof filter {      
        FilterByFirstName first_name = 1;
        FilterByLastName last_name = 2;
   }
}

message FilterByFirstName {
    string value = 1;
}

message FilterByLastName {
    string value = 1;
}

message UpdateUserRequest {
    User user = 1;
    google.protobuf.FieldMask field_mask = 2;
}

message UpdateUserResponse {
    User user = 1;
}

message DeleteUserRequest {
    int64 id = 1;
}

message DeleteUserResponse {

}

